up:
	docker-compose up -d
stop:
	docker-compose stop
down:
	docker-compose down
ssh_app:
	docker-compose exec app bash
ssh_web:
	docker-compose exec web bash
migrate:
	docker-compose exec app php artisan migrate
tinker:
	docker-compose exec app php artisan tinker